"""add database constraints and indexes

Revision ID: e6a9d44b2bed
Revises: e7186a76a172
Create Date: 2026-07-07 10:39:27.568061
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'e6a9d44b2bed'
down_revision: str | None = 'e7186a76a172'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_account_occurred_on', ['account_id', 'occurred_on'], unique=False)
        batch_op.create_index('ix_transactions_user_occurred_on', ['user_id', 'occurred_on'], unique=False)
        batch_op.create_index('ix_transactions_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index('ix_transactions_user_type', ['user_id', 'type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_user_type')
        batch_op.drop_index('ix_transactions_user_status')
        batch_op.drop_index('ix_transactions_user_occurred_on')
        batch_op.drop_index('ix_transactions_account_occurred_on')

    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###

